version: "3.7"

services:

    netstacker-controller:
      build:
          context: .
          dockerfile: ./dockerfiles/netstacker_controller_dockerfile
      environment:
          - NET_TEXTFSM=/usr/local/lib/python3.8/site-packages/ntc_templates/templates/
          - NETSTACKER_CONFIG=/code/config/config.json
          - NETSTACKER_LOG_CONFIG_FILENAME=/code/config/log-config.yml
      ports:
          - "9000:9000"
      networks:
          - "netstacker-network"
      depends_on:
          - redis
      restart: always

    netstacker-worker-pinned:
      build:
          context: .
          dockerfile: ./dockerfiles/netstacker_pinned_worker_dockerfile
      environment:
        - NET_TEXTFSM=/usr/local/lib/python3.8/site-packages/ntc_templates/templates/
        - NETSTACKER_CONFIG=/code/config/config.json
        - NETSTACKER_LOG_CONFIG_FILENAME=/code/config/log-config.yml
      depends_on:
        - redis
      networks:
      - "netstacker-network"
      restart: always

    netstacker-worker-fifo:
      build:
          context: .
          dockerfile: ./dockerfiles/netstacker_fifo_worker_dockerfile
      environment:
        - NET_TEXTFSM=/usr/local/lib/python3.8/site-packages/ntc_templates/templates/
        - NETSTACKER_CONFIG=/code/config/config.json
        - NETSTACKER_LOG_CONFIG_FILENAME=/code/config/log-config.yml
      depends_on:
        - redis
      networks:
      - "netstacker-network"
      restart: always

    redis:
      build:
        context: .
        dockerfile: ./dockerfiles/netstacker_redis_dockerfile
      networks:
      - "netstacker-network"
      restart: always

networks:

  netstacker-network:
    name: "netstacker-network"
